### ISSUE TITLE
Different OMR

### ISSUE THREAD

**Issue by Pancham1603** [N-A-C-S/OMR-Checker-Demo#1]
could you please let me know where to make changes in `omr_main.py` such that it can support a different OMR sheet. Trying to make it work with this one
![bvn_omr](https://user-images.githubusercontent.com/70520879/135605038-b9b3973d-7f69-4216-a04f-f60180aaa178.png)

It would be great if you could set it for ques 1-5...will follow for the rest

**Comment by sortedcord** [comment]
Are there any vulnerabilities in this? (I kinda didn't study for my Chemistry Test and I really need a good grade)

**Comment by Pancham1603** [comment]
@sortedcord i ended up making my own thing for this purpose but still there's a lot to work on. Have got 2 days for the CS paper. Will try to make it work :')

**Comment by ABX9801** [comment]
@Pancham1603  sorry for replying very late.  The code is hardcoded according to the OMR sheet displayed on the app. I  hope you altered it accordingly. I'll be happy to help otherwise.
